package util;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public class LoadTables {

	public void creatScherma(Connection c) throws SQLException {
		
		
		Statement stmt = c.createStatement();
		
/* POSTGRES
		stmt.execute("CREATE TABLE MESAS ( ID SERIAL PRIMARY KEY,  IDENTIFICACAO VARCHAR(255),"
				+ " ANDAR  VARCHAR(255), FRANQUIA_ID INTEGER, TIPO_ID INTEGER );");
		stmt.execute("CREATE TABLE CLIENTES ( ID Serial PRIMARY KEY,  NOME VARCHAR(255),"
				+ " CPF  VARCHAR(255), TELEFONE VARCHAR(255), ENDERECO VARCHAR(255), DESCRICAO  VARCHAR(255) );");
		stmt.execute("CREATE TABLE FRANQUIAS ( ID SERIAL PRIMARY KEY,  NOME VARCHAR(255),"
				+ " FRANQUEADO_ID  INTEGER, LOCAL VARCHAR(255), HORA_FUN TIME );");
		stmt.execute("ALTER TABLE MESAS ADD FOREIGN KEY (FRANQUIA_ID) REFERENCES FRANQUIAS(ID);");
		stmt.execute("CREATE TABLE TIPOS ( ID SERIAL PRIMARY KEY, NOME VARCHAR(255), DESCRICAO  VARCHAR(255));");
		stmt.execute("ALTER TABLE MESAS ADD FOREIGN KEY (TIPO_ID) REFERENCES TIPOS(ID);");
		stmt.execute("CREATE TABLE USUARIOS ( ID SERIAL  PRIMARY KEY, LOGIN VARCHAR(255) UNIQUE, SENHA VARCHAR(255),"
				+ "FRANQUEADO_ID INTEGER UNIQUE, FUNCAO INTEGER);");
		stmt.execute("CREATE TABLE RESERVAS ( ID SERIAL PRIMARY KEY, PESSOAS VARCHAR(255), DESCRICAO  VARCHAR(255), "
				+ "DATA DATE, HORA_INICIO TIME, HORA_FIM TIME, MESA_ID INTEGER, CLIENTE_ID INTEGER);");
		stmt.execute("ALTER TABLE RESERVAS ADD FOREIGN KEY (MESA_ID) REFERENCES MESAS(ID);");
		stmt.execute("ALTER TABLE RESERVAS ADD FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID)");
		stmt.execute("CREATE TABLE FRANQUEADOS ( ID INTEGER PRIMARY KEY,  NOME VARCHAR(255),"
				+ " CPF VARCHAR(255), TELEFONE VARCHAR(255), ENDERECO VARCHAR(255),EMAIL VARCHAR(255) UNIQUE);");
		stmt.execute("ALTER TABLE FRANQUIAS ADD FOREIGN KEY (FRANQUEADO_ID) REFERENCES FRANQUEADOS(ID)");
		stmt.execute("ALTER TABLE USUARIOS ADD FOREIGN KEY (FRANQUEADO_ID) REFERENCES FRANQUEADOS(ID)");
		stmt.execute("INSERT INTO USUARIOS (LOGIN,SENHA,FUNCAO) VALUES ('ADMIN','123',2);");
		
		*/
		/*
		stmt.execute("CREATE TABLE MESAS ( ID INTEGER IDENTITY PRIMARY KEY,  IDENTIFICACAO VARCHAR(255),"
				+ " ANDAR  VARCHAR(255), FRANQUIA_ID INTEGER, TIPO_ID INTEGER );");
		stmt.execute("CREATE TABLE CLIENTES ( ID INTEGER IDENTITY PRIMARY KEY,  NOME VARCHAR(255),"
				+ " CPF  VARCHAR(255), TELEFONE VARCHAR(255), ENDERECO VARCHAR(255), DESCRICAO  VARCHAR(255) );");
		stmt.execute("CREATE TABLE FRANQUIAS ( ID INTEGER IDENTITY PRIMARY KEY,  NOME VARCHAR(255),"
				+ " FRANQUEADO_ID  INTEGER, LOCAL VARCHAR(255), HORA_FUN TIME );");
		stmt.execute("ALTER TABLE MESAS ADD FOREIGN KEY (FRANQUIA_ID) REFERENCES FRANQUIAS(ID);");
		stmt.execute("CREATE TABLE TIPOS ( ID INTEGER IDENTITY PRIMARY KEY, NOME VARCHAR(255), DESCRICAO  VARCHAR(255));");
		stmt.execute("ALTER TABLE MESAS ADD FOREIGN KEY (TIPO_ID) REFERENCES TIPOS(ID);");
		stmt.execute("CREATE TABLE USUARIOS ( ID INTEGER IDENTITY  PRIMARY KEY, LOGIN VARCHAR(255) UNIQUE, SENHA VARCHAR(255),"
				+ "FRANQUEADO_ID INTEGER UNIQUE, FUNCAO INTEGER);");
		stmt.execute("CREATE TABLE RESERVAS ( ID INTEGER IDENTITY PRIMARY KEY, PESSOAS VARCHAR(255), DESCRICAO  VARCHAR(255), "
				+ "DATA DATE, HORA_INICIO TIME, HORA_FIM TIME, MESA_ID INTEGER, CLIENTE_ID INTEGER);");
		stmt.execute("ALTER TABLE RESERVAS ADD FOREIGN KEY (MESA_ID) REFERENCES MESAS(ID);");
		stmt.execute("ALTER TABLE RESERVAS ADD FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID)");
		stmt.execute("CREATE TABLE FRANQUEADOS ( ID INTEGER PRIMARY KEY,  NOME VARCHAR(255),"
				+ " CPF VARCHAR(255), TELEFONE VARCHAR(255), ENDERECO VARCHAR(255),EMAIL VARCHAR(255) UNIQUE);");
		stmt.execute("ALTER TABLE FRANQUIAS ADD FOREIGN KEY (FRANQUEADO_ID) REFERENCES FRANQUEADOS(ID)");
		stmt.execute("ALTER TABLE USUARIOS ADD FOREIGN KEY (FRANQUEADO_ID) REFERENCES FRANQUEADOS(ID)");
		stmt.execute("INSERT INTO USUARIOS (LOGIN,SENHA,FUNCAO) VALUES ('ADMIN','123',2);");
		
		*/
		
		 stmt.execute("CREATE TABLE MESAS ("
		 		+ " MESAS_ID SERIAL PRIMARY KEY,"
		 		+ " MESAS_IDENTIFICACAO VARCHAR(255),"
		 		+ " MESAS_ANDAR  VARCHAR(255),"
		 		+ "FRANQUIA_ID INTEGER,"
		 		+ "TIPO_ID INTEGER );");
				 
				stmt.execute("CREATE TABLE CLIENTES ("
						+ "CLIENTES_ID Serial PRIMARY KEY,"
						+ "CLIENTES_NOME VARCHAR(255),"
						+ "CLIENTES_CPF  VARCHAR(255),"
						+ "CLIENTES_TELEFONE VARCHAR(255),"
						+ "CLIENTES_ENDERECO VARCHAR(255),"
						+ "CLIENTES_DESCRICAO VARCHAR(255) );");
				    
				stmt.execute("CREATE TABLE FRANQUIAS ("
						+ "FRANQUIAS_ID SERIAL PRIMARY KEY,"
						+ "FRANQUIAS_NOME VARCHAR(255),"
						+ "LOCAL VARCHAR(255),"
						+ "FRANQUIAS_HORA_FUN TIME,"
						+ "FRANQUEADO_ID  INTEGER);");
						
				 stmt.execute("ALTER TABLE MESAS "
				 		+ "ADD FOREIGN KEY (FRANQUIA_ID) "
				 		+ "REFERENCES FRANQUIAS(FRANQUIAS_ID);");
					
				stmt.execute("CREATE TABLE TIPOS ("
						+ "TIPOS_ID SERIAL PRIMARY KEY,"
						+ "TIPOS_NOME VARCHAR(255),"
						+ "TIPOS_DESCRICAO VARCHAR(255));");
						
				stmt.execute("ALTER TABLE MESAS "
						+ "ADD FOREIGN KEY (TIPO_ID)"
						+ " REFERENCES TIPOS(TIPOS_ID);");

				stmt.execute("CREATE TABLE USUARIOS ("
						+ "USUARIOS_ID SERIAL  PRIMARY KEY,"
						+ "USUARIOS_LOGIN VARCHAR(255) UNIQUE,"
						+ "USUARIOS_SENHA VARCHAR(255),"
						+ "FRANQUEADO_ID INTEGER UNIQUE,"
						+ "USUARIOS_FUNCAO INTEGER,"
						+ "USUARIOS_FOTO BYTEA  );");

				stmt.execute("CREATE TABLE RESERVAS ("
						+ "RESERVAS_ID SERIAL PRIMARY KEY,"
						+ "RESERVAS_QTD_PESSOAS VARCHAR(255),"
						+ "RESERVAS_DESCRICAO  VARCHAR(255),"
						+ "RESERVAS_DATA DATE,"
						+ "RESERVAS_HORA_INICIO TIME,"
						+ "RESERVAS_HORA_FIM TIME,"
						+ "MESA_ID INTEGER,"
						+ "CLIENTE_ID INTEGER);");
				    
				stmt.execute("ALTER TABLE RESERVAS "
						+ "ADD FOREIGN KEY (MESA_ID) "
						+ "REFERENCES MESAS(MESAS_ID);");

				stmt.execute("ALTER TABLE RESERVAS"
						+ " ADD FOREIGN KEY (CLIENTE_ID)"
						+ " REFERENCES CLIENTES(CLIENTES_ID);");

				stmt.execute("CREATE TABLE FRANQUEADOS ("
						+ "FRANQUEADOS_ID INTEGER PRIMARY KEY,"
						+ "FRANQUEADOS_NOME VARCHAR(255),"
						+ "FRANQUEADOS_CPF VARCHAR(255),"
						+ "FRANQUEADOS_TELEFONE VARCHAR(255),"
						+ "FRANQUEADOS_ENDERECO VARCHAR(255),"
						+ "FRANQUEADOS_EMAIL VARCHAR(255) UNIQUE);");
					
				stmt.execute("ALTER TABLE FRANQUIAS"
						+ " ADD FOREIGN KEY (FRANQUEADO_ID)	"
						+ "REFERENCES FRANQUEADOS(FRANQUEADOS_ID);");

				stmt.execute("ALTER TABLE USUARIOS"
						+ " ADD FOREIGN KEY (FRANQUEADO_ID) "
						+ "REFERENCES FRANQUEADOS(FRANQUEADOS_ID);");

				stmt.execute("INSERT INTO USUARIOS ("
						+ "USUARIOS_LOGIN,"
						+ "USUARIOS_SENHA,"
						+ "USUARIOS_FUNCAO) "
						+ "VALUES ('ADMIN','123',2);");
				
	}
}
